[versions]
shadow = "8.1.0"
spotless = "6.12.0"

[plugins]

[libraries]
adventure = "net.kyori:adventure-api:4.13.1"
aikar-commands = "co.aikar:acf-core:0.5.1-SNAPSHOT"
caffeine = "com.github.ben-manes.caffeine:caffeine:3.1.6"
jetbrains-annotations = "org.jetbrains:annotations:24.0.0"
junit = "org.junit.jupiter:junit-jupiter-engine:5.9.2"
minestom = "com.github.Minestom:Minestom:80f5db34a6"
onesky = "info.datamuse:onesky-java:1.0.0-alpha"
redisson = "org.redisson:redisson:3.21.0"
