name: 'publish'
on: [ push, workflow_dispatch ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GRADLE_PROPERTIES: ${{ secrets.GRADLE_PROPERTIES }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Setup java'
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: 'Setup gradle properties'
        shell: bash
        run: |
          mkdir -p ~/.gradle/
          echo "GRADLE_USER_HOME=${HOME}/.gradle" >> $GITHUB_ENV
          echo "${GRADLE_PROPERTIES}" > ~/.gradle/gradle.properties

      - name: 'Publish artifact'
        run: |
          chmod +x gradlew
          ./gradlew publishAllPublicationsToSkyPlexRepository --no-daemon
